### ISSUE TITLE
m parameter

### ISSUE THREAD

**Issue by nbuton** [ymirsky/KitNET-py#1]
Hi,

I have a question on the m parameter, if we set m to 1 we only have auto encoder with an input dimension of 1, so how do you avoid to learn the identity ? Maybe I misunderstood something.

**Comment by ymirsky** [comment]
Because a single autoencoder has an encoding layer which is smaller than
the input layer. This forces the network to learn meaningful summaries of
the data.

**Comment by nbuton** [comment]
Yes but if the Input layer is allready of dimension 1. We cannot reduce more than 1. So the encoding layer will be size one.

**Comment by ymirsky** [comment]
Ah yes, I misunderstood you. When m=1 it means that the maximum input for any autoencoder in the ensemble layer should be at most 1. So yes, these autoencoders are one dimensional. However, the output layer will have 1 input for every autoencoder in the ensemble layer. So, in essence, the entire architecture reduces to one wide autoencoder (the output layer). Of course, the output autoencoder will have compression in its hidden layer.

**Comment by nbuton** [comment]
Ok, but the autoencoder in the output layer, take as entry the RMSE of the n(number of statistics) one dimensional auto encoder(Ensemble layer) ? And if these previous autoencoder(ensemble layer) are one dimensional they will learn the identity and then their RMSE will be allways 0. So the output layer autoencoder will have as entry always n zeros ?

**Comment by ymirsky** [comment]
It is more likely that there will be large mistakes since one neuron will have trouble fitting the distribution of the input feature. As a result, the RMSE distribution will likely reflect the original distribution.

Regardless, I highly recommend mot setting m to small values, especially m=1. This is because the purpose of the ensemble layer is to learn meaningful representations from sets of features, to thus make the collective computation more efficient. If you are setting m=1, you are better off not using KitNET and rather using a regular autoencoder. 

Hope this helps
